version: '3'

services:
  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: mailpit
    restart: unless-stopped
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_UI_PORT:-8025}:8025'
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge

volumes:
  mailpit-data:
